### PR TITLE
CMake: allow disabling the intermediate objects target (cryptopp-object).

### PR DESCRIPTION
**Pull request by HeinrichJanzing**
Targets with only object inputs do not work correctly with some
generators (like Xcode, see issue #355). Defining these directly in
terms of the source code files (rather than a reused set of object
files) allows correct builds in such cases. This can now be controlled
through a new option USE_INTERMEDIATE_OBJECTS_TARGET which defaults to
ON.

### CODE REVIEW

**Comment by noloader** [comment]
@HeinrichJanzing,

Please forgive my ignorance. What targets are you having trouble with? The expected Crypto++ artifacts are `libcryptopp.a`, `libcryptopp.so` and `cryptest.exe`. I believe Cmake provides all three.

**Comment by HeinrichJanzing** [comment]
They are indeed defined but in my experience, when using Xcode as the generator, they are never actually built, as described in the referenced issue #355. Both library targets fail to result in an actual library subsequently causing the cryptest.exe artifact to fail to build as well.

**Comment by noloader** [comment]
> Both library targets fail to result in an actual library subsequently causing the cryptest.exe artifact to fail to build as well.

OK, thanks.

I think this is why Wei provided `adhoc.ccp.proto`. It predates Xcode, so I'm guessing it was added for Borland or Sun Studio or Metrowerks or some other old IDE.

What I am thinking... Can you add a recipe for Xcode that:

1. copies `adhoc.ccp.proto` to `adhoc.ccp`
2. adds the source file `adhoc.ccp` to the Xocde library targets?

My apologies for not doing it. I know very little about Cmake, and I really struggle with it.

**Comment by noloader** [comment]
Merged. Thank you very much.

**Pull request merged**
