### PR TITLE
improve runtime exception messages

### PR DESCRIPTION
**Pull request by Arzaghi**
Improve runtime exception messages to guide the user to choose correct value for each invalid parameter

### CODE REVIEW

**Comment by noloader** [comment]
@mouse07410,

Any thoughts on this?

**Comment by Arzaghi** [comment]
> @mouse07410,
> 
> Any thoughts on this?

I decided to use this amazing library but finding the correct values for different parameters of different algorithms was quite difficult. so I decided to improve runtime exception messages. so anybody on higher level of applications can use these messages to find the reasons of the problem and how to choose correct values.

**Comment by expnkx** [comment]
> > @mouse07410,
> > Any thoughts on this?
> 
> I decided to use this amazing library but finding the correct values for different parameters of different algorithms was quite difficult. so I decided to improve runtime exception messages. so anybody on higher level of applications can use these messages to find the reasons of the problem and how to choose correct values.

I think these issues will only get systematically solved after herb sutter's deterministic exceptions got added into C++.

**Comment by noloader** [comment]
I think we are going to pass on the PR. The problem is, we risk breaking scripts that call Crypto++ based programs. The original messages have been present for about 30 years. If the message changes it could have negative impact on others.

**Pull request closed without merging**
