### PR TITLE
NULLPTR fix for blake2 tests

### PR DESCRIPTION
**Pull request by c0ff**
Hope it is all now.

### CODE REVIEW

**Comment by noloader** [comment]
Also see this under GCC:

```
g++ -DNDEBUG -g2 -O2 -fPIC -pipe -c dlltest.cpp
g++ -DNDEBUG -g2 -O2 -fPIC -pipe -c adhoc.cpp
validat3.cpp: In function ‘bool CryptoPP::Test::ValidateBLAKE2s()’:
validat3.cpp:1482:27: error: expected primary-expression before ‘unsigned’
    BLAKE2s blake2s(false, unsigned int(tests[i].dlen));
                           ^
validat3.cpp:1488:93: error: expected primary-expression before ‘unsigned’
    BLAKE2s blake2s((const byte*)tests[i].key, tests[i].klen, NULLPTR, 0, NULLPTR, 0, false, unsigned int(tests[i].dlen));
                                                                                             ^
validat3.cpp: In function ‘bool CryptoPP::Test::ValidateBLAKE2b()’:
validat3.cpp:1913:27: error: expected primary-expression before ‘unsigned’
    BLAKE2b blake2b(false, unsigned int(tests[i].dlen));
                           ^
validat3.cpp:1919:93: error: expected primary-expression before ‘unsigned’
    BLAKE2b blake2b((const byte*)tests[i].key, tests[i].klen, NULLPTR, 0, NULLPTR, 0, false, unsigned int(tests[i].dlen));
                                                                                             ^
make: *** [validat3.o] Error 1
make: *** Waiting for unfinished jobs....
ERROR: failed to make cryptest.exe

```

**Comment by c0ff** [comment]
Hmm, I don't understand what's the problem. `unsigned int(x)` should be a valid constructor

**Comment by c0ff** [comment]
May be it is not anymore in C++17. I'd use static_cast<unsigned int>() instead then.

**Comment by noloader** [comment]
> Hmm, I don't understand what's the problem. unsigned int(x) should be a valid constructor

Probably related to the [vexing parse](https://en.wikipedia.org/wiki/Most_vexing_parse) problem, but I'm not one to split hairs about it. If it breaks the compile it needs to be fixed :)

**Comment by noloader** [comment]
That cleared the compile error. Thanks.

**Pull request merged**
