### PR TITLE
Recommend & Add CHAM Block Cipher(x86,x64)

### PR DESCRIPTION
**Pull request by dinoHee**
Hi!
This is Korean Block Cipher CHAM.
[https://books.google.co.kr/books?id=SoBSDwAAQBAJ&pg=PA5&lpg=PA5&dq=CHAM+block+family&source=bl&ots=uTPPJsI87x&sig=dfq84vgdBGHbNTDe6tE-4_MbJw4&hl=ko&sa=X&ved=0ahUKEwjl0pSnxLnbAhUIO7wKHQOjBFIQ6AEIODAC#v=onepage&q=CHAM%20block%20family&f=false](url)

We implemented cham block cipher algorithm, and we want to show you.
Plz see these, and re-comment.

### CODE REVIEW

**Comment by noloader** [comment]
Thanks @dinoHee,

I think this needs a little work before adding it to the library.

Email me at *noloader, gmail* account.

**Comment by dinoHee** [comment]
Thanks @noloader .
I will email to you!

**Comment by noloader** [comment]
This pull request is being worked on Kim Sung Hee's GitHub at [dinohee GitHub](https://github.com/dinoHee/cryptopp ).

**Comment by dinoHee** [comment]
Hi jeff!

It was a late night for our contry when you email!

I send you collaborator and here is the link

https://github.com/dinoHee/cryptopp/invitations
-----Original Message-----

**Comment by noloader** [comment]
This pull request is being worked on Kim Sung Hee's GitHub at [Dinohee | Crypto++](https://github.com/dinoHee/cryptopp). Closing the Pull Request for the time being.

**Comment by noloader** [comment]
@dinoHee,

The updated/integrated CHAM is ready for a Pull Request. It is a optimized C++ implementation. The 32-bit versions run around 10-11 cpb (128-bit key) and 12-13 cpb (256-bit key).

The cipher resisted SSE multiblock optimizations. Or maybe, it resisted SSE4 (and below) multiblock optimizations. I tested a rough SSE4 implementation and it ran around 17 cpb (128-bit key) and 15 cpb (256-bit key).

CHAM resisted for two reasons, which trace back to design. First, SSE4 does not have the gather/scatter instructions needed to quickly pack and unpack words. Second, SSE4 does not have bit rotates so a rotate effectively took 3 SSE instructions (two SHIFTS and an OR).

CHAM may witness a speedup with AVX2, but I did not test it. AVX2 will allow the gather (loads) and the bit rotates. However, AVX2 lacks the scatters (stores). At the moment the library does not pursue AVX2. Instead we aim for SSE2 through SSE4 which is found on nearly x86 machine. 

I can show you how to add the inline ASM next, if you would like. I'm not going to work that part. I don't get that excited over ASM anymore.

**Comment by noloader** [comment]
I've been trying to speed-up CHAM64 on 32-bit machines (especially the low-end ones). Below are the numbers on an old VIA C7-D processor from the early 2000's. It is 32-bit and has SSE2 only (and not SSE3 or above). The VIA has a single core and runs at 1.7 GHz.

* ASM:
    * CHAM-64(128)/CTR (128-bit key)<TD>4<TD>378.1<TD>0.886<TD>1506
    * CHAM-128(128)/CTR (128-bit key)<TD>29<TD>55.5<TD>0.833<TD>1416
    * CHAM-128(256)/CTR (256-bit key)<TD>27<TD>59.7<TD>0.901<TD>1532

* C++:
    * CHAM-64(128)/CTR (128-bit key)<TD>11<TD>148.7<TD>0.888<TD>1510
    * CHAM-128(128)/CTR (128-bit key)<TD>29<TD>56.5<TD>0.839<TD>1426
    * CHAM-128(256)/CTR (256-bit key)<TD>27<TD>59.7<TD>0.900<TD>1529

From the numbers above, C++ is 148.7 cpb while the ASM is 378 cpb. The ASM is below and I lifted it from `cham64_encrypt`.

Do you see anything wrong with the ASM?

-----

```
#if (CRYPTOPP_SSE2_ASM_AVAILABLE)
void CHAM64_Enc_SSE(word16* block, const word16* subKeys)
{
#ifdef __GNUC__
	__asm __volatile
	(
		INTEL_NOPREFIX
#else
	__asm
	{
#endif
		// AS1( pushad )
		AS_PUSH_IF86( bp )
		//AS_PUSH_IF86( bx )

#ifdef __GNUC__
		ATT_NOPREFIX
		AS2( mov WORD_REG(si), %[block] )
		AS_PUSH_IF86( si )
		AS2( mov WORD_REG(cx), %[subKeys] )
		AS_PUSH_IF86( cx )
		INTEL_NOPREFIX
#else
		AS2( mov WORD_REG(si), [block] )
		AS_PUSH_IF86( si )
		AS2( mov WORD_REG(cx), [subKeys] )
		AS_PUSH_IF86( cx )
#endif

		AS1( cld )           // direction flag auto-incrementing
		AS1( lodsw )         // esi에서 WORD(16bit)만큼 읽어 eax에 복사, esi 주소 이동
		AS2( xchg ax, bp )   // x0 == bp
		AS1( lodsw )
		AS2( xchg ax, bx )   // x1 == bx
		AS1( lodsw )
		AS2( xchg ax, dx )   // x2 == dx
		AS1( lodsw )
		AS2( xchg ax, si )   // x3 == si
		AS2( xor ax, ax )    // eax = 0

	ASL( 0 )                 // loop_v0
		AS_POP_IF86( cx )
		AS2( mov WORD_REG(di), WORD_REG(cx) )
		AS_PUSH_IF86( cx )
		ASJ( jmp, 2, f )

	ASL( 1 )                    // loop_v1
		AS2( test al, 15 )      // (al&15==0)이면 (ZF=1)
		ASJ( jz, 0, b )         // jump if zero (ZF=1)

	ASL( 2 )                    // loop_v2
		AS_PUSH_IF86( ax )      // save i
		AS2( mov cx, 0x0108 )
		AS2( test al, 1 )       // (al&1==0)이면 (ZF=1) => if((i%2) == 0)
		ASJ( jnz, 3, f )        // ZF=0 이면 3로
		AS2( xchg ch, cl )

	ASL( 3 )                     // loop_v3
		AS2( xor bp, ax )        // in[0] ^ i
		AS2( mov ax, bx )  
		AS2( rol ax, cl )        // i==even일때 cl=1, odd일때 cl=8 // ROL16(x[1], 1)
		AS2( xor ax, di )        // ROL16(x[1], 1) ^ rk[i]
		AS1( scasw )             // 레지스터와 메모리 값 비교(edi word만큼 이동 = rk[i+1])
		AS2( add bp, ax )        // (x[0] ^ i) + ((ROL16(x[1], 1) ^ rk[i % (2 * KW)])
		AS2( xchg cl, ch )  
		AS2( rol bp, cl )        // ROL16((x[0] ^ i) + ((ROL16(x[1], 1) ^ rk[i % (2 * KW)]), 8)

		AS2( xchg bp, bx )
		AS2( xchg bx, dx )
		AS2( xchg dx, si )

		AS_POP_IF86( ax )
		AS2( add al, 1 )
		AS2( cmp al, 80 )
		ASJ( jne, 1, b )          // ZF=0 이면 1

		AS_POP_IF86( cx )
		AS_POP_IF86( di )
		AS2( xchg ax, bp )
		AS1( stosw )              // eax 값을 WORD(16bit)만큼 읽어 edi 주소에 복사, edi 주소 이동
		AS2( xchg ax, bx )
		AS1( stosw )
		AS2( xchg ax, dx )
		AS1( stosw )
		AS2( xchg ax, si )
		AS1( stosw )

		// AS1( popad )
		//AS_POP_IF86( bx )
		AS_POP_IF86( bp )

#ifdef __GNUC__
		ATT_NOPREFIX
		: "+m" (*(char (*)[2*4])block)
		: [block] "S" (block), [subKeys] "c" (subKeys), "m" (*(const char (*)[2*16])subKeys)
# if (CRYPTOPP_BOOL_X64 || CRYPTOPP_BOOL_X32)
		: "rax", "rbx", "rdx", "rdi", "cc"
# else
		: "eax", "ebx", "edx", "edi", "cc"
# endif
		);
#else
	}
#endif  // __GNUC__
}
#endif  // CRYPTOPP_SSE2_ASM_AVAILABLE
```

**Pull request closed without merging**
