### PR TITLE
C++17 compatible lambda expressions to replace `bind2nd`

### PR DESCRIPTION
**Pull request by KayEss**
This will fix issue #558 

This first commit is just to make sure that we're all happy with this approach. if so I'll move forwards and make the other changes needed.

### CODE REVIEW

**Comment by noloader** [comment]
Thanks @KayEss,

Give me some time to run it on a few machines.

**Comment by noloader** [comment]
Thanks again @KayEss,

The change tested OK under Linux, OS X and Windows. Let's try the whole bunch.

**Comment by noloader** [comment]
Ugh, this just surfaced. You can duplicate it with:

```
CXXFLAGS="-DDEBUG -g3 -O1 -std=c++03" make asan -j 4
```

Result:

```
passed:  128 default encryptions and decryptions
=================================================================
==22425==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x62100079f433 at pc 0x000000b2d400 bp 0x7ffc35594f20 sp 0x7ffc35594f10
READ of size 1 at 0x62100079f433 thread T0
    #0 0xb2d3ff in std::not_equal_to<unsigned char>::operator()(unsigned char const&, unsigned char const&) const /usr/include/c++/7/bits/stl_function.h:366
    #1 0xb2d3ff in std::binder2nd<std::not_equal_to<unsigned char> >::operator()(unsigned char&) const /usr/include/c++/7/backward/binders.h:164
    #2 0xb2d3ff in bool __gnu_cxx::__ops::_Iter_pred<std::binder2nd<std::not_equal_to<unsigned char> > >::operator()<unsigned char*>(unsigned char*) /usr/include/c++/7/bits/predefined_ops.h:283
    #3 0xb2d3ff in unsigned char* std::__find_if<unsigned char*, __gnu_cxx::__ops::_Iter_pred<std::binder2nd<std::not_equal_to<unsigned char> > > >(unsigned char*, unsigned char*, __gnu_cxx::__ops::_Iter_pred<std::binder2nd<std::not_equal_to<unsigned char> > >, std::random_access_iterator_tag) /usr/include/c++/7/bits/stl_algo.h:120
    #4 0xb2d3ff in unsigned char* std::__find_if<unsigned char*, __gnu_cxx::__ops::_Iter_pred<std::binder2nd<std::not_equal_to<unsigned char> > > >(unsigned char*, unsigned char*, __gnu_cxx::__ops::_Iter_pred<std::binder2nd<std::not_equal_to<unsigned char> > >) /usr/include/c++/7/bits/stl_algo.h:162
    #5 0xb2d3ff in unsigned char* std::find_if<unsigned char*, std::binder2nd<std::not_equal_to<unsigned char> > >(unsigned char*, unsigned char*, std::binder2nd<std::not_equal_to<unsigned char> >) /usr/include/c++/7/bits/stl_algo.h:3933
    #6 0xb2d3ff in CryptoPP::StreamTransformationFilter::LastPut(unsigned char const*, unsigned long) /home/jwalton/cryptopp/filters.cpp:830
    #7 0xb2613a in CryptoPP::FilterWithBufferedInput::PutMaybeModifiable(unsigned char*, unsigned long, int, bool, bool) /home/jwalton/cryptopp/filters.cpp:430
    #8 0x4488a0 in CryptoPP::FilterWithBufferedInput::Put2(unsigned char const*, unsigned long, int, bool) /home/jwalton/cryptopp/filters.h:337
    #9 0x9a2803 in CryptoPP::BufferedTransformation::MessageEnd(int, bool) /home/jwalton/cryptopp/cryptlib.h:1565
    #10 0x9a2803 in CryptoPP::DataDecryptor<CryptoPP::Rijndael, CryptoPP::SHA256, CryptoPP::DataParametersInfo<16u, 16u, 32u, 8u, 2500u> >::LastPut(unsigned char const*, unsigned long) /home/jwalton/cryptopp/default.cpp:181
    #11 0xb2613a in CryptoPP::FilterWithBufferedInput::PutMaybeModifiable(unsigned char*, unsigned long, int, bool, bool) /home/jwalton/cryptopp/filters.cpp:430
    #12 0x4488a0 in CryptoPP::FilterWithBufferedInput::Put2(unsigned char const*, unsigned long, int, bool) /home/jwalton/cryptopp/filters.h:337
    #13 0x9a214c in CryptoPP::BufferedTransformation::MessageEnd(int, bool) /home/jwalton/cryptopp/cryptlib.h:1565
    #14 0x9a214c in CryptoPP::DataDecryptorWithMAC<CryptoPP::Rijndael, CryptoPP::SHA256, CryptoPP::HMAC<CryptoPP::SHA256>, CryptoPP::DataParametersInfo<16u, 16u, 32u, 8u, 2500u> >::LastPut(unsigned char const*, unsigned long) /home/jwalton/cryptopp/default.cpp:290
    #15 0xb2613a in CryptoPP::FilterWithBufferedInput::PutMaybeModifiable(unsigned char*, unsigned long, int, bool, bool) /home/jwalton/cryptopp/filters.cpp:430
    #16 0x4488a0 in CryptoPP::FilterWithBufferedInput::Put2(unsigned char const*, unsigned long, int, bool) /home/jwalton/cryptopp/filters.h:337
    #17 0x85fca6 in CryptoPP::BufferedTransformation::ChannelPut2(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned char const*, unsigned long, int, bool) /home/jwalton/cryptopp/cryptlib.cpp:444
    #18 0x851b10 in CryptoPP::BufferedTransformation::ChannelMessageEnd(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, bool) /home/jwalton/cryptopp/cryptlib.h:2039
    #19 0x851b10 in CryptoPP::BufferedTransformation::TransferMessagesTo2(CryptoPP::BufferedTransformation&, unsigned int&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool) /home/jwalton/cryptopp/cryptlib.cpp:601
    #20 0x8536e6 in CryptoPP::BufferedTransformation::TransferAllTo2(CryptoPP::BufferedTransformation&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool) /home/jwalton/cryptopp/cryptlib.cpp:642
    #21 0x448864 in CryptoPP::SourceTemplate<CryptoPP::StringStore>::PumpAll2(bool) /home/jwalton/cryptopp/filters.h:1396
    #22 0x5c4b9e in CryptoPP::Source::PumpAll() /home/jwalton/cryptopp/filters.h:1338
    #23 0x5c4b9e in CryptoPP::Source::SourceInitialize(bool, CryptoPP::NameValuePairs const&) /home/jwalton/cryptopp/filters.h:1371
    #24 0x5c4b9e in CryptoPP::StringSource::StringSource(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, CryptoPP::BufferedTransformation*) /home/jwalton/cryptopp/filters.h:1439
    #25 0x5740c1 in CryptoPP::Test::TestEncryptors() /home/jwalton/cryptopp/validat0.cpp:482
    #26 0x6077dd in CryptoPP::Test::ValidateAll(bool) /home/jwalton/cryptopp/validat1.cpp:111
    #27 0x4250de in CryptoPP::Test::Validate(int, bool, char const*) /home/jwalton/cryptopp/test.cpp:868
    #28 0x443241 in CryptoPP::Test::scoped_main(int, char**) /home/jwalton/cryptopp/test.cpp:364
    #29 0x444710 in main /home/jwalton/cryptopp/test.cpp:986
    #30 0x7fb376727009 in __libc_start_main (/lib64/libc.so.6+0x21009)
    #31 0x4233b9 in _start (/home/jwalton/cryptopp/cryptest.exe+0x4233b9)

0x62100079f433 is located 205 bytes to the left of 4096-byte region [0x62100079f500,0x6210007a0500)
allocated by thread T0 here:
    #0 0x7fb3776d8850 in malloc (/lib64/libasan.so.4+0xde850)
    #1 0xc4db91 in CryptoPP::UnalignedAllocate(unsigned long) /home/jwalton/cryptopp/misc.cpp:324
    #2 0x499d95 in CryptoPP::AllocatorWithCleanup<unsigned char, false>::allocate(unsigned long, void const*) /home/jwalton/cryptopp/secblock.h:206
    #3 0x499d95 in CryptoPP::AllocatorWithCleanup<unsigned char, false>::pointer CryptoPP::StandardReallocate<unsigned char, CryptoPP::AllocatorWithCleanup<unsigned char, false> >(CryptoPP::AllocatorWithCleanup<unsigned char, false>&, unsigned char*, CryptoPP::AllocatorWithCleanup<unsigned char, false>::size_type, CryptoPP::AllocatorWithCleanup<unsigned char, false>::size_type, bool) /home/jwalton/cryptopp/secblock.h:159
    #4 0xb16890 in CryptoPP::AllocatorWithCleanup<unsigned char, false>::reallocate(unsigned char*, unsigned long, unsigned long, bool) /home/jwalton/cryptopp/secblock.h:248
    #5 0xb16890 in CryptoPP::SecBlock<unsigned char, CryptoPP::AllocatorWithCleanup<unsigned char, false> >::New(unsigned long) /home/jwalton/cryptopp/secblock.h:736
    #6 0xb16890 in CryptoPP::FilterPutSpaceHelper::HelpCreatePutSpace(CryptoPP::BufferedTransformation&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long, unsigned long, unsigned long&) /home/jwalton/cryptopp/filters.h:188
    #7 0xb21ff2 in CryptoPP::StreamTransformationFilter::NextPutMultiple(unsigned char const*, unsigned long) /home/jwalton/cryptopp/filters.cpp:671
    #8 0xb2602f in CryptoPP::FilterWithBufferedInput::NextPutMaybeModifiable(unsigned char*, unsigned long, bool) /home/jwalton/cryptopp/filters.h:398
    #9 0xb2602f in CryptoPP::FilterWithBufferedInput::PutMaybeModifiable(unsigned char*, unsigned long, int, bool, bool) /home/jwalton/cryptopp/filters.cpp:413
    #10 0x4488a0 in CryptoPP::FilterWithBufferedInput::Put2(unsigned char const*, unsigned long, int, bool) /home/jwalton/cryptopp/filters.h:337
    #11 0xb189c6 in CryptoPP::BufferedTransformation::Put(unsigned char const*, unsigned long, bool) /home/jwalton/cryptopp/cryptlib.h:1513
    #12 0xb189c6 in CryptoPP::ProxyFilter::NextPutMultiple(unsigned char const*, unsigned long) /home/jwalton/cryptopp/filters.cpp:511
    #13 0xb25ae3 in CryptoPP::FilterWithBufferedInput::NextPutMaybeModifiable(unsigned char*, unsigned long, bool) /home/jwalton/cryptopp/filters.h:398
    #14 0xb25ae3 in CryptoPP::FilterWithBufferedInput::PutMaybeModifiable(unsigned char*, unsigned long, int, bool, bool) /home/jwalton/cryptopp/filters.cpp:387
    #15 0x4488a0 in CryptoPP::FilterWithBufferedInput::Put2(unsigned char const*, unsigned long, int, bool) /home/jwalton/cryptopp/filters.h:337
    #16 0xb189c6 in CryptoPP::BufferedTransformation::Put(unsigned char const*, unsigned long, bool) /home/jwalton/cryptopp/cryptlib.h:1513
    #17 0xb189c6 in CryptoPP::ProxyFilter::NextPutMultiple(unsigned char const*, unsigned long) /home/jwalton/cryptopp/filters.cpp:511
    #18 0xb25ae3 in CryptoPP::FilterWithBufferedInput::NextPutMaybeModifiable(unsigned char*, unsigned long, bool) /home/jwalton/cryptopp/filters.h:398
    #19 0xb25ae3 in CryptoPP::FilterWithBufferedInput::PutMaybeModifiable(unsigned char*, unsigned long, int, bool, bool) /home/jwalton/cryptopp/filters.cpp:387
    #20 0x4488a0 in CryptoPP::FilterWithBufferedInput::Put2(unsigned char const*, unsigned long, int, bool) /home/jwalton/cryptopp/filters.h:337
    #21 0x85fca6 in CryptoPP::BufferedTransformation::ChannelPut2(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned char const*, unsigned long, int, bool) /home/jwalton/cryptopp/cryptlib.cpp:444
    #22 0xb19d76 in CryptoPP::StringStore::CopyRangeTo2(CryptoPP::BufferedTransformation&, unsigned long&, unsigned long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool) const /home/jwalton/cryptopp/filters.cpp:1216
    #23 0xb19bad in CryptoPP::StringStore::TransferTo2(CryptoPP::BufferedTransformation&, unsigned long&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool) /home/jwalton/cryptopp/filters.cpp:1206
    #24 0x8518cf in CryptoPP::BufferedTransformation::TransferMessagesTo2(CryptoPP::BufferedTransformation&, unsigned int&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool) /home/jwalton/cryptopp/cryptlib.cpp:596
    #25 0x8536e6 in CryptoPP::BufferedTransformation::TransferAllTo2(CryptoPP::BufferedTransformation&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool) /home/jwalton/cryptopp/cryptlib.cpp:642
    #26 0x448864 in CryptoPP::SourceTemplate<CryptoPP::StringStore>::PumpAll2(bool) /home/jwalton/cryptopp/filters.h:1396
    #27 0x5c4b9e in CryptoPP::Source::PumpAll() /home/jwalton/cryptopp/filters.h:1338
    #28 0x5c4b9e in CryptoPP::Source::SourceInitialize(bool, CryptoPP::NameValuePairs const&) /home/jwalton/cryptopp/filters.h:1371
    #29 0x5c4b9e in CryptoPP::StringSource::StringSource(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, CryptoPP::BufferedTransformation*) /home/jwalton/cryptopp/filters.h:1439
    #30 0x5740c1 in CryptoPP::Test::TestEncryptors() /home/jwalton/cryptopp/validat0.cpp:482
    #31 0x6077dd in CryptoPP::Test::ValidateAll(bool) /home/jwalton/cryptopp/validat1.cpp:111
    #32 0x4250de in CryptoPP::Test::Validate(int, bool, char const*) /home/jwalton/cryptopp/test.cpp:868
    #33 0x443241 in CryptoPP::Test::scoped_main(int, char**) /home/jwalton/cryptopp/test.cpp:364
    #34 0x444710 in main /home/jwalton/cryptopp/test.cpp:986
    #35 0x7fb376727009 in __libc_start_main (/lib64/libc.so.6+0x21009)

SUMMARY: AddressSanitizer: heap-buffer-overflow /usr/include/c++/7/bits/stl_function.h:366 in std::not_equal_to<unsigned char>::operator()(unsigned char const&, unsigned char const&) const
Shadow bytes around the buggy address:
  0x0c42800ebe30: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c42800ebe40: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c42800ebe50: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c42800ebe60: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c42800ebe70: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
=>0x0c42800ebe80: fa fa fa fa fa fa[fa]fa fa fa fa fa fa fa fa fa
  0x0c42800ebe90: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c42800ebea0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c42800ebeb0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c42800ebec0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c42800ebed0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==22425==ABORTING
ERROR: failed to execute validation suite
Using seed: 1515504762
```

**Comment by KayEss** [comment]
I ran the make command you gave and it doesn't report any error. I guess I need to run `cryptest.exe tv` with one of the test vectors. Which one is giving the problem?

    make clean
    CXXFLAGS="-DDEBUG -g3 -O1 -std=c++03" make asan -j4
    for FL in $(ls TestVectors/); do LD_PRELOAD=libasan.so.4 ./cryptest.exe tv TestVectors/$FL; done

In the results I got some errors like these:

    CryptoPP::Exception caught: ObjectFactoryRegistry: could not find factory for algorithm AES/OCB
    Skipping to next test.

I'm on Ubuntu 17.10 and g++ (Ubuntu 7.2.0-8ubuntu3) 7.2.0

As for the `ptrdiff_t` thing, I don't get what could possibly be wrong :) Is the test covering a case of badly formed data so the find_if finds something and the exception should be thrown? I've looked at the expressions and I can't see I did something stupid with the expressions, and `find_if` is returning a `byte*`

It's late here so I'll try to re-write it by duplicating the whole if inside the conditional compilation. I'll change that now and run the tests again overnight and if that looks good then push it in the morning.

**Comment by noloader** [comment]
> I ran the make command you gave and it doesn't report any error. I guess I need to run `cryptest.exe tv` with one of the test vectors.

I'm seeing it with `cryptest.exe v` on the Fedora 27 machine. I'm thinking there's a subtle problem with the change or the C++ std library. Let's just side-step it.

Duplicate things so that `std::find_if` and throw are in both blocks. That seems to restore order. Something like:

```
diff --git a/filters.cpp b/filters.cpp
index 51a214c..954b3a2 100644
--- a/filters.cpp
+++ b/filters.cpp
@@ -821,8 +821,14 @@ void StreamTransformationFilter::LastPut(const byte *inString, size_t length)
                        if (m_padding == PKCS_PADDING)
                        {
                                byte pad = space[s-1];
+#if defined(CRYPTOPP_CXX11_LAMBDA)^M
+                               const byte * pos = std::find_if(space+s-pad, space+s, [pad](const byte b) { return b != pad; });^M
+                               if (pad < 1 || pad > s || pos != space+s)^M
+                                       throw InvalidCiphertext("StreamTransformationFilter: invalid PKCS #7 block padding found");^M
+#else^M
                                if (pad < 1 || pad > s || std::find_if(space+s-pad, space+s, std::bind2nd(std::not_equal_to<byte>(), pad)) != space+s)
                                        throw InvalidCiphertext("StreamTransformationFilter: invalid PKCS #7 block padding found");
+#endif^M
                                length = s-pad;
                        }
```

This is one of the reasons `cryptest.sh` is important. It catches these kinds of oddities.

**Comment by KayEss** [comment]
I still can't for the life of me understand why one of them would fire the bug and not the other. Is the c++17 version also run through the gcc address sanitiser? I've gone a little bit more conservative with the change.

**Comment by KayEss** [comment]
That looks much nicer to me, and will make changes to the rest of the locations much simpler. If we're all happy with this it should now be real easy to fix the other places it's used.

**Comment by zabulus** [comment]
I suggest go ahead and use custom implementation:
```
template<class InputIterator, , class T>
  InputIterator find_if_not (InputIterator first, InputIterator last, const T& val)
  while (first!=last) {
    if (*first != val) return first;
    ++first;
  }
  return last;
```
This compatible with C++03, C++11 and above, removes ifdef, bind2nd and lambda function. Easy, straightforward and maintainable. 
What do you think?

**Comment by noloader** [comment]
Thanks @KayEss,

The latest change is testing good. Two small suggestions for this round. First, place the library version in `misc.h`. That's were a lot of the utility stuff that does not fit elsewhere lives.

Second, consider changing the name from `find_if_not` to avoid confusion with symbols in `std::`. When I saw the use in `StreamTransformationFilter::LastPut` I though I needed to add ` std::`. I realized what was happening. A name like `FindIfNot` should avoid the confusion.

Also, some people will have a `using namespace std;` and include the Crypto++ header. Later, we will take the bug report about the ambiguity. I find it best to avoid questions and bug reports before they happen.

The library does not always follow the second item. For example, the library supplies a `memcpy_s` that mirrors a Microsoft safer string function. It caused problems on MinGW or Cygwin or MSYS, if I recall correctly.

**Comment by KayEss** [comment]
Now changed use to `FindIfNot` throughout. I've tested c++03 and c++1z with gcc asan locally and all tests pass here.

I think I prefer the version built on top of `std::find_if` simply because it's higher level and thus more obviously correct than the `while` loop. The more I try to follow Sean Parent's advice about no raw loops the more I like it :) I guess there is also a tiny chance it'd be better able to take advantage of clever implementations from the standard library maintainers?

Happy to change if the consensus goes the other way though.

**Comment by noloader** [comment]
Things tested OK this morning, so we merged. Thanks to everyone who helped with it.

**Pull request merged**
