### PR TITLE
Add vcpkg installation instructions

### PR DESCRIPTION
**Pull request by PhoebeHui**
Cryptopp is available as a port in VCPKG , documenting the install process here will help users get started by providing a single set of commands to build cryptopp, ready to be included in their projects.

VCPKG is a C++ library manager that simplifies installation for cryptopp and other project dependencies, we also test whether our library ports build in various configurations (dynamic, static) on various platforms (OSX, Linux, Windows: x86, x64, UWP, ARM) to keep a wide coverage for users.

I'm a maintainer for vcpkg, and here is what the port script looks like. We try to keep the library maintained as close as possible to the original library.

### CODE REVIEW

**Comment by noloader** [comment]
Thank you very much.

**Comment by PhoebeHui** [comment]
Thanks for your help!

**Comment by noloader** [comment]
@PhoebeHui,

Another library you may be interested in providing (if you have not done so) is [Botan](https://github.com/randombit/botan). It is a C++ security and TLS library by Jack Lloyd and his team. It is a hidden gem on the web.

Ping @randombit.

**Comment by PhoebeHui** [comment]
@noloader, thanks for mentioning this, the instructions has been added to [wiki ](https://github.com/randombit/botan/wiki/Distros).

**Pull request merged**
