### PR TITLE
Fix calling multiple ZlibDecompressor in parallel causes adler32 chec…

### PR DESCRIPTION
**Pull request by rocksonhead**
…ksum failure (GH #596)

### CODE REVIEW

**Comment by noloader** [comment]
Ping @denisbider, @mouse07410 and @denisbider.

Any objections?

**Comment by denisbider** [comment]
@noloader: Looks reasonable to me.

**Comment by mouse07410** [comment]
No objections. The logic of the proposed fix is convincing.

**Comment by noloader** [comment]
Thank you very much.

**Pull request merged**
