### PR TITLE
Add dll export on some iterhash classes to fix CMake shared build.

### PR DESCRIPTION
**Pull request by egorpugin**

### CODE REVIEW

**Comment by noloader** [comment]
This will likely break things for the static library when its being used to compliment the FIPS DLL. You can test the change by opening the Visual Studio solution, and then doing a Build → Batch Build → Build All. All 22 projects need to build correctly.

**Comment by egorpugin** [comment]
Do you have some CI system like appveyor or travis?

**Comment by egorpugin** [comment]
Yes, there're errors. That's why I asked if you ok with that PR.
It seems I won't be able to resolve those errors, because I'm not familiar with provided sln build structure.

**Comment by egorpugin** [comment]
What about the following?
```
#ifndef CRYPTOPP_ENABLE_COMPLIANCE_WITH_FIPS_140_2
#define CRYPTOPP_DLL_NO_FIPS CRYPTOPP_DLL
#else
#define CRYPTOPP_DLL_NO_FIPS 
#endif

class CRYPTOPP_DLL_NO_FIPS CRYPTOPP_NO_VTABLE IteratedHashBase : public BASE
```

**Comment by noloader** [comment]
@egorpugin, I'm going to close this PR. I'll add some documentation on how to build a *Regular DLL* on Windows.

**Pull request closed without merging**
