### PR TITLE
Fix Windows compilation issues

### PR DESCRIPTION
**Pull request by RaptorFactor**
This fixes compilation under:

- Any compiler on Windows with /DUNICODE
- MSVC with /std:c++latest
- MSVC targeting ARM
- Clang-cl (i.e. Clang pretending to be MSVC) targeting x86/x64

### CODE REVIEW

**Comment by RaptorFactor** [comment]
Which parts will break C++03? I can look to see if I can fix that.

Also all the tests pass for me when targeting clang-cl. The declspec(novtable) problem is already worked around in this patch, and that was the only runtime error when running the tests.

**Comment by MarcelRaad** [comment]
> Also all the tests pass for me when targeting clang-cl. The declspec(novtable) problem is already worked around in this patch, and that was the only runtime error when running the tests.

Works for me too, there's no crash anymore 👍 

> The workaround I implemented to remove std::bind2nd should work in C++03, because both std::bind and std::placeholders::_1 are present in C++03.

Unfortunately only in TR1, and in its std::tr1 namespace.

**Comment by RaptorFactor** [comment]
Doh you're right. Been too long since I've had to use C++03 (though to be fair C++11 has been widely available for half a decade).

I'm not sure of a good workaround in that case.... I could do a version check on __cplusplus if that's acceptable and just provide both implementations?

**Comment by noloader** [comment]
I'm willing to meet you half way:

1. Leave the "unsupported" in place. Users who want it can experiment.
2. Leave the `std::bind2nd` in place. I test under 6 compilers from C++03 through C++17 and it has never caused a problem.
3. Don't use `std::placeholder` since its not C++03.
4. Take the `RDRAND`, `RDSEED`, `Integer`, `_M_ARM` and `OutputDebugString` changes.

The reason  for (1) is I had to take on CMake maintenance because the folks who wanted it mostly lost interest after we added `CMakeList.txt`. I don't want Clang on Windows maintenance because I know how difficult Clang is to work with at times.

I'm not sure about `__crt_debugger_hook`. I test compiles under ARM with `cryptest.nmake` and I have never encountered a problem. What is the issue?

The `OutputDebugString` changes were on the table a while ago. No one was interested in the change at the time, so things were left as-is. Also see [Issue 385, Don't use WSAStringToAddress, use WSAStringToAddressA instead](https://github.com/weidai11/cryptopp/issues/385#issuecomment-286436615).

If interested in maintaining LLVM on Windows support, you should set up some VMs with Vista through Windows 10 and VS2008 through VS2015 and test it more thoroughly. The earliest LLVM on Windows download is Clang 3.4. Some problems are just unsolvable, like that standard header problem.

**Comment by MarcelRaad** [comment]
@noloader @RaptorFactor 
> 1.Leave the "unsupported" in place. Users who want it can experiment.

Maybe something like this would be OK so that we can just define something in the project file instead of patching the library after every update?

```
// Clang pretends to be VC++, too.  
//   See http://github.com/weidai11/cryptopp/issues/147  
#if defined(_MSC_VER) && defined(__clang__) && !defined(CRYPTOPP_ENABLE_UNSUPPORTED_MSVC_CLANG)
# error: "Unsupported configuration"  
#endif  
```

**Comment by noloader** [comment]
Does anyone know where we are with this PR?

I see `std::bind2nd` is still missing, and using `std::bind` and `std::placeholders` instead. If I am parsing things correctly, it looks like the original PR.

**Comment by MarcelRaad** [comment]
Yes, the "Fix compilation with MSVC and /std:c++latest" commit still breaks C++03. Could you please remove it from this PR @RaptorFactor and maybe make another PR for that issue replacing them conditionally on C++11 support? Probably a new feature macro for std::bind support in config.h would make sense.

Or you could just cherry-pick the other commits from refs/pull/397/head @noloader.

**Comment by noloader** [comment]
Marcel provided a PR that removed the things that would break C++03. Also see [Pull Request 444](https://github.com/weidai11/cryptopp/pull/444).

We merged the updated PR today. Closing this PR.

Thanks for everyone's help with it.

**Pull request closed without merging**
