### PR TITLE
fixed Keccak and SHA3 to support HMAC

### PR DESCRIPTION
**Pull request by DevJPM**
added the blocksize constant and member functions to Keccak and SHA3
(and all derivatives) as well as some compile-time-checks

### CODE REVIEW

**Comment by DevJPM** [comment]
This is the fix for the SHA-3 / Keccak with HMAC issue I promised to deliver after 5.6.4 in Issue #257

**Comment by noloader** [comment]
Sorry about not commenting sooner. This fell off the radar. Do you have plans to make `r()` dynamic or runtime configurable? If not, do you see any problems with tweaking:

```
unsigned int BlockSize() const { return r(); }
```

To:

```
unsigned int BlockSize() const { return BLOCKSIZE; }
```

**Comment by noloader** [comment]
The second comment is, iterated hashes based on DM-constructions have block sizes. Should we [publicly?] overload `BlockSize()` for a sponge construction:

```
unsigned int BlockSize() const { ... }
```

To toss an alternative out there:

```

public:
    unsigned int SpongeSize() const { ... }

protected:
    unsigned int BlockSize() const { ... }
```

For the classes that need access to operate the cipher, we can use friendship.

Or is this just overkill?

**Comment by DevJPM** [comment]
> Do you have plans to make `r()` dynamic or runtime configurable?

If we plan to allow for dynamic permutation-selection, then yes, we have to make this one dynamic. However I'd much prefer making the permutation a template parameter (at least for the instantiation) if possible. And the second reason to delegate to r() was to push the instantiation into the base class, so we don't have to place the BlockSize() definition in _all_ derived classes (because BLOCKSIZE is unknown at the upper level).

As for hiding the block-size, I don't really think this is a good idea as it's the library standard not to hide it and it would kinda break the "contract" that blocksize is guaranteed to be accessible by anybody. If you feel better, we could indeed add a SpongeSize() / BitRate() / AbsorptionRate() function to clarify the meaning of BlockSize (inline-defaulting to BlockSize())

**Comment by noloader** [comment]
> If we plan to allow for dynamic permutation-selection, then yes, we have to make this one dynamic. However I'd much prefer making the permutation a template parameter

OK, good. It also disconnect `r()` from `CRYPTOPP_CONSTANT(BLOCKSIZE = 200 - 2 * DIGESTSIZE)` :)

Do you feel like making the change? I'll get it merged shortly.

I'm also going to merge @MarcelRaad's changes to the VS project files after getting an issue documented for it (change control; not a bug). The issue report will allow us to back it out quickly by making it easy to locate. Take a look over the diff's he provided at https://github.com/weidai11/cryptopp/pull/286 and https://patch-diff.githubusercontent.com/raw/weidai11/cryptopp/pull/286.diff .

**Comment by DevJPM** [comment]
> Do you feel like making the change?

I'm kinda confused right now which change you mean? Moving the BlockSize functions into the derived classes and redefining them to be BLOCKSIZE?

**Comment by noloader** [comment]
> Moving the BlockSize functions into the derived classes and redefining them to be BLOCKSIZE?

My bad... This one:

```
CRYPTOPP_CONSTANT(BLOCKSIZE = 200 - 2 * DIGESTSIZE)
unsigned int BlockSize() const { return BLOCKSIZE; }
```

Or is that wrong?

**Comment by DevJPM** [comment]
@noloader updated.

**Comment by noloader** [comment]
Thank you very much.

**Comment by noloader** [comment]
Also se [Commit de04771aa8af7ec8](http://github.com/weidai11/cryptopp/commit/de04771aa8af7ec8afdbd47af3a5773f553579bf).

**Pull request merged**
