### PR TITLE
Gunzip: added GetFilename() and GetComment() methods

### PR DESCRIPTION
**Pull request by c0ff**
We use this in our software. Pretty trivial to add because they were processed anyway.

### CODE REVIEW

**Comment by noloader** [comment]
Thanks @c0ff.

I think we are good, and we don't need this change. A patch is already available at [Gzip](https://www.cryptopp.com/wiki/Gzip) on the Crypto++ wiki.

**Comment by c0ff** [comment]
Oh, never new it. Thanks for the tip.

**Comment by noloader** [comment]
@c0ff,

Upon reflection, maybe we should add the functionality to Gzip. I asked on the mailing list at [Add Filename, Filetime and Comment support to Gzip?](https://groups.google.com/forum/#!topic/cryptopp-users/FB8b02N5utI).

Let's see what the community wants.

**Comment by noloader** [comment]
@c0ff,

There's some user interest in this functionality, so we've reopened the PR.

Please look over the patch at [Gzip | Patch](https://www.cryptopp.com/wiki/Gzip#Patch) when you have some time. Then, provide a PR for the Filenames, Filetimes and Comments.

Thanks.

**Comment by c0ff** [comment]
Looks like I created a little mess with commits. There are only 2 useful commits and 3 others are noops. Sorry.
People on StackOverflow say that https://robots.thoughtbot.com/keeping-a-github-fork-updated works not so well with GitHub, I could not push my commits until I found this: http://stackoverflow.com/questions/10298291/cannot-push-to-github-keeps-saying-need-merge/39289521#39289521

**Comment by c0ff** [comment]
If you want to keep the history clean,  I can redo the things, just need to know how.

**Comment by noloader** [comment]
> Looks like I created a little mess with commits. 

Yeah, I know what you mean. I've done it to others when making a PR.

What I did for Botan recently was cancel the old PR, and then create a new PR. There's an extra PR request, but it keeps history clean. Also see [Add ARIA Block Cipher (PR #1005)](https://github.com/randombit/botan/pull/1005) and [Add ARIA Block Cipher (PR #1014)](https://github.com/randombit/botan/pull/1014).

**Comment by noloader** [comment]
@c0ff,

I did one of those squahing commits. See [Squash your commits](https://github.com/blog/2141-squash-your-commits) on GitHub help.

Thanks for the contribution.

**Comment by c0ff** [comment]
Looks like I managed to clean this up.
So now there are 2 commits: my original attempt, and the merged gzip.diff - reformatted to match the code style.
I ran gzip/gunzip test with cryptest.exe - all seems fine, no exception, files match.

**Comment by noloader** [comment]
Also see [Issue 420](https://github.com/weidai11/cryptopp/issues/420).

**Pull request merged**
