### PR TITLE
Make ECIES default compatible with BouncyCastle

### PR DESCRIPTION
**Pull request by mouse07410**

### CODE REVIEW

**Comment by noloader** [comment]
Also see [Issue 21: ECIES uses byte count, and not bit count, for label size](http://github.com/weidai11/cryptopp/issues/21).

**Comment by noloader** [comment]
@mouse07410,

What do you think about spinning up a ***ecies*** dev-branch, and then aligning `DLIES` and `ECIES` with Bouncy Castle?

**Comment by mouse07410** [comment]
> What do you think about spinning up a ecies dev-branch, and then aligning DLIES and ECIES with Bouncy Castle?

No idea about DLIES, but for ECIES the patch is 3 lines (OK, maybe 6 - I don't remember), and it's been already tested with BC up to 1.55 and the current GitHub master. I don't want to start a whole separate branch bureaucracy for such a simple change (especially since it doesn't look like we've got a bunch of users banging on our doors demanding to preserve the old incompatible ECIES behavior). All my tests here are done with it#216 applied (because I don't have use for a library that's not compatible with BC :).

I think we should just merge #216 (the ECIES fix) into the master for 5.7, and be done with it.

**Comment by noloader** [comment]
> I don't want to start a whole separate branch bureaucracy for such a simple change

Lol... That put milk up my nose.

Don't take those simple changes for granted :) I can't recount how many times I risked being tarred and feathered by users because a  simple change had unforeseen side effects :)

Also, I think we want to completely align with Bouncy Castle and Botan here. That is, we want things to "just work" for users. Performing the fix on ECIES means DLIES could have issues, so its not a complete remediation in security engineering parlance. We will definitly want to give DLIES its due attention.

I'll spin-up the ECIES branch to help with mods and testing. When you see the branch appear, please make a PR against it.

**Comment by noloader** [comment]
Also see [Commit c3e2e0fb25fd](http://github.com/weidai11/cryptopp/commit/c3e2e0fb25fd1fa25e3a6e8eadb9ef78e8158be9).

**Pull request closed without merging**
